apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
  namespace: app
spec:
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 0.1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: ClusterIP
